# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carros Aula' do
    use_frameworks!
    pod 'JSONModel', '~> 1.7'
    pod 'SMXMLDocument', '~> 1.1'
    workspace 'MyWorkspace'
end
